language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r dev-reqs.txt
  - pip install codecov
# command to run tests
script:
  - make check
  - make check-import
  - make test
  - codecov
